version: '2'
services:
  customer-service:
    build: ./customer-service
    ports:
     - "8080:8080"
  order-service:
    build: ./order-service
    ports:
     - "8081:8080"
    depends_on:
     - customer-service
  product-service:
    build: ./product-service
    ports:
     - "8082:8080"