server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doc-tool
    username: root
  jpa:
      hibernate:
        ddl-auto: create
