def semver = input message: 'Increase the patch, minor, major version', parameters: [choice(choices: "patch\nminor\nmajor", description: 'Increase the patch, minor, major version', name: 'SEM_VERSION')]
node {
    stage('Checkout'){
        dir('microdocs-core-ts'){
            echo "Checkout git"
            git url: 'git@github.com:MaxxtonGroup/microdocs.git', branch: 'development'
            stash name: 'src'
        }
    }
    stage('Build'){
        dir('microdocs-core-ts'){
            echo "Installing npm dependencies"
            unstash 'src'
            sh 'npm version ' + semver
            sh 'npm install'
            stash name: 'build'
        }
    }

    stage('Test'){
        dir('microdocs-core-ts'){
            echo "Test"
            unstash 'build'
            sh 'npm test'
        }
    }

    stage('PrePublish'){
        dir('microdocs-core-ts'){
            echo "PrePublish"
            unstash 'build'
            sh 'npm run prepublish'
            dir('dist'){
                stash 'dist'
            }
        }
    }

    stage('Publish'){
        dir('microdocs-core-ts/dist'){
            echo "Publish"
            unstash 'dist'
            sh 'echo @maxxton:registry=https://npm.maxxton.com > .npmrc'
            sh 'npm publish'
        }
    }

    // stage('Tag Git'){
    //     sh 'echo @maxxton:registry=https://npm.maxxton.com > .npmrc'
    //     def version = sh 'npm view @maxxton/microdocs-cli version'
    //     sh 'git tag microdocs-core_' + version
    //     sh 'git push --tags'
    // }
}