default:
  logLevel: info
  port: 3000
  basePath: /api/v1
  tempFolder: tmp
  staticFolder: ../microdocs-ui/dist;../microdocs-ui/node_modules
  viewFolder: views
  dataFolder: data

  application-name: Maxxton Software
  application-version: 1.0
  application-description: Maxxton Software rest api
  application-schema: http
  application-host: localhost:8000
  application-basePath: ''

