version: '3'
services:
  microdocs-server:
    build:
      context: ../../
      dockerfile: ./microdocs/microdocs-server/Dockerfile
    ports:
     - 3000:3000
     - 5858:5858
    volumes:
     - ../../microdocs-core/dist:/app/@maxxton/microdocs-server/node_modules/@maxxton/microdocs-core
     - ../microdocs-ui/dist:/app/@maxxton/microdocs-ui/dist:ro
     - ./src:/app/@maxxton/microdocs-server/src:ro
     - ./data:/app/@maxxton/microdocs-server/data
     - ./dist:/app/@maxxton/microdocs-server/dist
